### ISSUE TITLE
Leave Landing Page

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#1]
## Leave Landing Page

**Value Statement**  
As a user I want to leave the landing page so that I can either browse through all the sights or use the filter.

**Description**  
![LP](https://user-images.githubusercontent.com/71886503/120648798-553d4680-c47c-11eb-8679-0ed166bc9cb7.png)

**Acceptance Criteria**
- [x] Click on a button that leads user somewhere
- [x] See all button: show all sights
- [x] Filter button: show filter page

**Complexity**
M

**Tasks**
- [x] new feature branch 'landing-page'
- [x] add landing page to 'pages' folder
- [x] implement connection between LP and All Sights
- [x] implement connection between LP and Filter page
- [x] add tests
