### ISSUE TITLE
Searchbar Sights

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#13]
Template

**Value Statement**
As a user, I want to enter a sight name into a search bar so that I do not have to scroll through all the sights for detailed info.

**Description**

**Acceptance Criteria**
- [x] type into search bar
- [x] show the correct sight(s)

**Complexity**
S

**Tasks**
- [x] new feature branch 'feat-searchbar'
- [x] implement search logic
