### ISSUE TITLE
Add Sight to Itinerary

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#14]
**Value Statement**
As a user, I want to add sights to a route so that I can have an overview of my planned trip. 

**Description**
![Bildschirmfoto 2021-06-18 um 11 39 55](https://user-images.githubusercontent.com/71886503/122543099-b09a3780-d02b-11eb-8bf9-a44c7eba252c.png)

**Acceptance Criteria**
- [x] add sight to route via add button
- [x] choose between different days
- [x] show sight in itinerary nav

**Complexity**
L

**Tasks**
- [x] new feature branch 'feat-itinerary'
- [x] add itinerary to nav
- [x] add add button to details view
- [x] add calendar to button
- [x] connect button logic to nav page
- [x] render sight(s) on correct day(s)
- [x] render days in chronological order
- [x] add component / page
