### ISSUE TITLE
render all counties

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#15]
**Value Statement**
As a user, I want to choose from all possible counties so that I can filter the sights according to my travel destination(s).

**Description**

**Acceptance Criteria**
- [x] show all counties in dropdown

**Complexity**
M

**Tasks**
- [x] new feature branch 'feat-searchoptions'
- [x] write function to get all counties as dropdown-friendly objects

**Comment by helenahcodes** [comment]
**Value Statement**
As a user, I want to see data so that I can see the sighta and basically use the app.

**Description**

**Acceptance Criteria**
- [ ] show sights

**Complexity**
L

**Tasks**
- [ ] new feature branch 'api-fetch'
- [ ] write fetch functions
- [ ] change existing code to include API data
- [ ] add tests
- [ ] add component / page
