### ISSUE TITLE
Sort Sights in Alphabetical Order

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#17]
**Value Statement**
As a user, I want to see all sights alphabetically ordered by county so that I have an idea of how far to scroll if I already have a specific sight or county in mind.

**Description**

**Acceptance Criteria**
- [x] show all sights in alphabetical order by county
- [x] show all dropdown options in alphabetical order

**Complexity**
S

**Tasks**
- [x] new branch 'sort-alphabetically'
- [x] add sort functions
