### ISSUE TITLE
Browse All Sights

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#2]
**Value Statement**
As a user, I want to see all the sights so that I can get ideas for travel destinations.

**Description**
![allsights](https://user-images.githubusercontent.com/71886503/120654032-9421cb00-c481-11eb-9240-9a382317cc2d.png)

**Acceptance Criteria**
- [x] see various sights

**Complexity**
M

**Tasks**
- [x] create feature branch 'sights' 
- [x] add all sights to pages folder
- [x] add sight card component
- [x] fill database / fetch sights
- [x] create sight card with picture, name and county
- [x] add favorites and details buttons
- [x] implement Favorites logic (toggle icons)
- [x] add styleguidist for sights card
