### ISSUE TITLE
Navigation Footer

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#3]
**Value Statement**
As a user, I want to be able to click on the icons in the nav footer so that I get from one page to the other.

**Description**
![footernav](https://user-images.githubusercontent.com/71886503/120656236-bae10100-c483-11eb-9d43-e2f07f9b2dfd.png)

**Acceptance Criteria**
- [x] click on an icon so I can get to the corresponding page

**Complexity**
S

**Tasks**
- [x] new feature branch 'navfooter'
- [x] add nav component
- [x] add icons
- [x] implement link logic to all icons and their respective pages
- [x] highlight active page
- [x] add tests
- [x] add styleguide component for navfooter
