### ISSUE TITLE
Filter Sights

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#4]
Template

**Value Statement**
As a user, I want to filter sights by county so that I can browse the ones I am most interested in.

**Description**
![filterpage](https://user-images.githubusercontent.com/71886503/120659026-3f348380-c486-11eb-9991-808b0043147f.png)

**Acceptance Criteria**
- [x]  select as many counties as I like from a dropdown menu
- [x] show results based on filters

**Complexity**
L

**Tasks**
- [x] new feature branch 'filter-page'
- [x] add component
- [x] add options in some way
- [x] implement filter logic
- [x] add styleguidist component for filter page
