### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#5]
Template

**Value Statement**
As a user, I want to see my favorites all in one place so that I do not have to search for them on the All Sights page again.

**Description**
![favorites](https://user-images.githubusercontent.com/71886503/120662583-8f611500-c489-11eb-9400-f3c635b9a24f.png)

**Acceptance Criteria**
- [x] see all favorites in one place 
- [x] click on shamrock to remove from favorites

**Complexity**
S

**Tasks**
- [x] new feature branch 'favorites'
- [x] add Favorites page to pages folder
- [x] implement favorites logic
