### ISSUE TITLE
Details View

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#6]
Template

**Value Statement**
As a user, I want to be able to see details of each sight so that I can get a better idea of it and see info like address, ticket price, and website.

**Description**
![details](https://user-images.githubusercontent.com/71886503/120664892-98eb7c80-c48b-11eb-9522-fda620a14cad.png)

**Acceptance Criteria**
- [x] show bigger photo
- [x] show details like the ones mentioned above, website opens on click (new window)
- [x] back button

**Complexity**
M

**Tasks**
- [x] new feature branch 'details'
- [x] add 'details' component
- [x] fetch and insert sight details
- [x] add Back button
