### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by heleah** [helenahcodes/adventeire#8]
**Value Statement**
As a user, I want to still see my favorites so that I do not have to add them anew. 

**Acceptance Criteria**
- [x] keep seeing faves after page reload

**Complexity**
S

**Tasks**
- [x] new feature branch 'local-storage'
- [x] new folder "lib"
- [x] local storage functions
- [x] useEffect for all sights
- [x] useEffect for fave sights
